In [1]:
import numpy as np

In [2]:
arr=np.arange(0,21)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
len(arr)

21

In [5]:
arr[2]

2

In [6]:
arr[-1]

20

In [7]:
arr[9]

9

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
arr[1:11:2]

array([1, 3, 5, 7, 9])

In [10]:
arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [11]:
arr < 100

array([ True,  True, False,  True, False,  True,  True, False])

In [12]:
arr2=np.array([True,True,False,False])

In [13]:
arr2

array([ True,  True, False, False])

In [14]:
np.where(arr2)

(array([0, 1], dtype=int64),)

In [15]:
arr[5]

18

In [16]:
arr[2]

1010

In [17]:
arr < 100
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [18]:
np.where(arr>100)

(array([2, 4, 7], dtype=int64),)

In [19]:
arr[np.where(arr>100)]=10
arr

array([ 1,  2, 10,  4, 10, 18, 71, 10])

In [20]:
np.where(arr<100)

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)

In [21]:
np.where(arr==10)

(array([2, 4, 7], dtype=int64),)

In [22]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[2]

array([35, 40, 45])

In [24]:
arr_2d[1][1]

25

In [25]:
arr_2d[1,1]

25

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [28]:
arr_2d[1:3,1:3]

array([[25, 30],
       [40, 45]])

In [29]:
arr_2d[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [30]:
arr_2d[0:3,2:]

array([[15],
       [30],
       [45]])

In [31]:
arr_2d[0:,:1]

array([[ 5],
       [20],
       [35]])

In [32]:
arr_2d[0:,2:]

array([[15],
       [30],
       [45]])

In [33]:
arr2d=np.zeros((10,7))
arr2d

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [34]:
arr2d.shape

(10, 7)

In [35]:
arr2d.shape[1]

7

In [36]:
arr_lenght = arr2d.shape[0]
arr_lenght

10

In [37]:
for i in range(arr_lenght):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9.]])

In [38]:
arr2d[4]

array([4., 4., 4., 4., 4., 4., 4.])

In [39]:
arr2d[[6,3,8]]

array([[6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8.]])

In [40]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7.]])